# Project: LLAZ2H
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = obj/kv.o obj/main.o
LINKOBJ  = obj/kv.o obj/main.o
LIBS     = -L"G:/Programs/Dev-Cpp/MinGW64/lib" -L"G:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"G:/Programs/Dev-Cpp/MinGW64/include" -I"G:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"G:/Dev/C/LLA/LLAZ2H/inc"
CXXINCS  = -I"G:/Programs/Dev-Cpp/MinGW64/include" -I"G:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"G:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"G:/Dev/C/LLA/LLAZ2H/inc"
BIN      = bin/LLAZ2H.exe
CXXFLAGS = $(CXXINCS) -Wall -g3
CFLAGS   = $(INCS) -Wall -g3 -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

obj/kv.o: src/kv.c
	$(CC) -c src/kv.c -o obj/kv.o $(CFLAGS)

obj/main.o: src/main.c
	$(CC) -c src/main.c -o obj/main.o $(CFLAGS)
